# Generated by Django 4.2.7 on 2023-11-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('numberOfParticpants', models.IntegerField(max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
