# Generated by Django 4.2.7 on 2023-11-05 23:10

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_group_code_group_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='creator',
            new_name='host',
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default=base.models.generateGroupCode, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='numberOfParticpants',
            field=models.IntegerField(),
        ),
    ]
