# Generated by Django 4.2.7 on 2023-11-09 02:31

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_creator_group_host_alter_group_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default=base.models.generateGroupCode, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('individualCode', models.CharField(max_length=10)),
                ('groupCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.group')),
            ],
        ),
    ]
