# Generated by Django 4.2.7 on 2023-11-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_group_id_alter_group_code_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='numberOfParticpants',
            new_name='numberOfParticipants',
        ),
    ]
