# Generated by Django 4.2.7 on 2023-11-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_numberofparticpants_group_numberofparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='budget',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
